[lint]
# Enable Pyflakes (`F`) and a subset pycodestyle warnings (`W`), flake8-bugbear (`B`) rules.
# McCabe complexity (`C901`) by default.
select = ["F", "W", "B"]
ignore = []

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Same as Black.
line-length = 88
indent-width = 4

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Extend excluded directories and file.
extend-exclude = = ["**/__pycache__", "**/.pytest_cache"]